import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import SessionProvider from "./components/SessionProver";
import SideNav from "./components/SideNav";
import Providers from "./components/Providers";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <Providers>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body>
          <SessionProvider>
            <div className="flex flex-col md:flex-row md:justify-center">
              <div className="top-0 w-full flex-none md:sticky md:h-screen md:w-64">
                <SideNav />
              </div>

              <div className="min-h-full w-full max-w-[980px] flex-grow border border-l-slate-200 md:overflow-y-auto">
                {children}
              </div>
            </div>
          </SessionProvider>
        </body>
      </html>
    </Providers>
  );
}
